# Generated by Django 4.0.2 on 2022-02-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='posted_image',
            new_name='gallery_image',
        ),
    ]
